# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chatbot_pb2 as chatbot__pb2

GRPC_GENERATED_VERSION = "1.75.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in chatbot_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class chatbot_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddChatRequest = channel.unary_unary(
            "/chatbot.chatbot_service/AddChatRequest",
            request_serializer=chatbot__pb2.AddRequest.SerializeToString,
            response_deserializer=chatbot__pb2.ResponseModel.FromString,
            _registered_method=True,
        )


class chatbot_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddChatRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_chatbot_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AddChatRequest": grpc.unary_unary_rpc_method_handler(
            servicer.AddChatRequest,
            request_deserializer=chatbot__pb2.AddRequest.FromString,
            response_serializer=chatbot__pb2.ResponseModel.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "chatbot.chatbot_service", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "chatbot.chatbot_service", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class chatbot_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddChatRequest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chatbot.chatbot_service/AddChatRequest",
            chatbot__pb2.AddRequest.SerializeToString,
            chatbot__pb2.ResponseModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
