# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"\x1d\n\nAddRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"!\n\rResponseModel\x12\x10\n\x08response\x18\x01 \x01(\t2P\n\x0f\x63hatbot_service\x12=\n\x0e\x41\x64\x64\x43hatRequest\x12\x13.chatbot.AddRequest\x1a\x16.chatbot.ResponseModelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=26
  _globals['_ADDREQUEST']._serialized_end=55
  _globals['_RESPONSEMODEL']._serialized_start=57
  _globals['_RESPONSEMODEL']._serialized_end=90
  _globals['_CHATBOT_SERVICE']._serialized_start=92
  _globals['_CHATBOT_SERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
