# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ocr_pb2 as ocr__pb2

GRPC_GENERATED_VERSION = "1.75.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in ocr_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class nrc_ocr_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddLicenceOCR = channel.unary_unary(
            "/nrc_ocr.nrc_ocr_service/AddLicenceOCR",
            request_serializer=ocr__pb2.AddLICENCEOCR.SerializeToString,
            response_deserializer=ocr__pb2.AddOutputNRC.FromString,
            _registered_method=True,
        )
        self.AddLicencePassport = channel.unary_unary(
            "/nrc_ocr.nrc_ocr_service/AddLicencePassport",
            request_serializer=ocr__pb2.AddLICENCEPASSPORT.SerializeToString,
            response_deserializer=ocr__pb2.AddOutputNRC.FromString,
            _registered_method=True,
        )


class nrc_ocr_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddLicenceOCR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddLicencePassport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_nrc_ocr_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AddLicenceOCR": grpc.unary_unary_rpc_method_handler(
            servicer.AddLicenceOCR,
            request_deserializer=ocr__pb2.AddLICENCEOCR.FromString,
            response_serializer=ocr__pb2.AddOutputNRC.SerializeToString,
        ),
        "AddLicencePassport": grpc.unary_unary_rpc_method_handler(
            servicer.AddLicencePassport,
            request_deserializer=ocr__pb2.AddLICENCEPASSPORT.FromString,
            response_serializer=ocr__pb2.AddOutputNRC.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nrc_ocr.nrc_ocr_service", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "nrc_ocr.nrc_ocr_service", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class nrc_ocr_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddLicenceOCR(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nrc_ocr.nrc_ocr_service/AddLicenceOCR",
            ocr__pb2.AddLICENCEOCR.SerializeToString,
            ocr__pb2.AddOutputNRC.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddLicencePassport(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nrc_ocr.nrc_ocr_service/AddLicencePassport",
            ocr__pb2.AddLICENCEPASSPORT.SerializeToString,
            ocr__pb2.AddOutputNRC.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
